name: Update RPCN Connector Docs

on:
  workflow_dispatch:
  repository_dispatch:  # Allows other repositories to trigger this workflow
    types: [generate-rpcn-docs]

jobs:
  generate-and-pr:
    runs-on: ubuntu-latest

    concurrency:
      group: update-rpcn-connector-docs
      cancel-in-progress: true

    env:
      NODE_VERSION: '18'
      DOCS_OVERRIDES: docs-data/overrides.json

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js (with npm cache)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install tools
        run: |
          npx doc-tools install-test-dependencies
          rpk connect install

      - name: Generate RPCN Connector docs
        id: generate
        run: |
          npx doc-tools generate rpcn-connector-docs \
            --fetch-connectors \
            --overrides $DOCS_OVERRIDES \
            --draft-missing > full_output.txt

          {
            echo "delta_report<<EOF"
            echo "<details><summary>RPCN Connector Generation Output</summary>"
            echo ""
            cat full_output.txt
            echo ""
            echo "</details>"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

          rm -f full_output.txt raw_delta.txt delta_report.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: auto-docs/update-rpcn-connector-docs
          title: 'auto-docs: Update RPCN connector docs'
          commit-message: 'docs: Update RPCN connector docs'
          body: ${{ steps.generate.outputs.delta_report }}
          labels: auto-docs
